name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: ./mvnw clean verify
        
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        if: success()
        with:
          files: target/site/jacoco/jacoco.xml 
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: FanyCastro/TradingSystem
